### ISSUE TITLE
Release 2.6.0 for jakartaEE

### ISSUE THREAD

**Issue by hazendaz** [hazendaz/sitemesh2#5]

**Comment by jaxhsu** [comment]
Does this support versions above Jakarta EE 9 and Servlet 5.0?

**Comment by hazendaz** [comment]
Not yet but that is the plan.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
@jaxhsu I've released milestone 1 for jakarta.  To get there the following had to go

- Dropped support for freemarker as it doesn't support jakarta
- Dropped support for velocity as it doesn't support jakarta
- Dropped support for tapestry as it doesn't support jakarta and we are too out of date.

Those are all optional usages here and my personal usage doesn't use any of those.

**Comment by jaxhsu** [comment]
@hazendaz Thank you for sharing. Currently, the version 2.6.0-M1 is running smoothly on my project.

**Comment by hazendaz** [comment]
Nice! Thanks for sharing your results.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
closing as completed.  Items that do not exist are listed separately for adding back when jakarta support is released for each of the three.
